# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gR6TzCqUZfnkDPJg9SrVmcPcy5wlHlua
"""

from __future__ import annotations

import argparse
import re
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt


BASE_COVARIATES = [
    "log_gdp_lag1",
    "inflation_annual_pct_lag1",
    "internet_usage_pct_lag1",
]

OUTCOME = "unemployment_rate"

DEFAULT_CSV = "Completed_Stage1_Audit_190-4.csv"
DEFAULT_XLSX = "DigitalNomadDataset copy.xlsx"


def parse_date_precision(value: object) -> str:
    """Identify whether an audit date contains year, month, or day precision."""
    if pd.isna(value):
        return "missing"
    s = str(value).strip()
    if re.fullmatch(r"\d{4}", s):
        return "year"
    if re.fullmatch(r"\d{4}[-/]\d{1,2}", s):
        return "month"
    if re.fullmatch(r"\d{1,2}/\d{1,2}/\d{2,4}", s):
        return "day"
    parsed = pd.to_datetime(s, errors="coerce")
    return "day" if pd.notna(parsed) else "other"


def parse_audit_date(value: object) -> pd.Timestamp:
    """Parse audit date values, returning NaT when unavailable."""
    if pd.isna(value):
        return pd.NaT
    return pd.to_datetime(str(value).strip(), errors="coerce")


def build_treatment_variables(audit: pd.DataFrame) -> pd.DataFrame:

    a = audit.copy()

    a["qualifying"] = (
        a["qualifying_program_found"]
        .astype("string")
        .str.lower()
        .eq("yes")
    )

    a["announcement_precision"] = a["announcement_date"].map(parse_date_precision)
    a["effective_precision"] = a["launch_or_effective_date"].map(parse_date_precision)

    a["announcement_date_parsed"] = a["announcement_date"].map(parse_audit_date)
    a["effective_date"] = a["launch_or_effective_date"].map(parse_audit_date)

    a["adoption_year"] = a["effective_date"].dt.year.astype("Int64")
    a["adoption_month"] = a["effective_date"].dt.month.astype("Int64")

    a["first_full_exposure_year"] = pd.Series(pd.NA, index=a.index, dtype="Int64")
    exact = a["qualifying"] & a["effective_date"].notna() & (
        a["effective_precision"].isin(["month", "day"])
    )
    jan = exact & a["adoption_month"].eq(1)
    non_jan = exact & a["adoption_month"].gt(1)

    a.loc[jan, "first_full_exposure_year"] = a.loc[jan, "adoption_year"]
    a.loc[non_jan, "first_full_exposure_year"] = (
        a.loc[non_jan, "adoption_year"] + 1
    )

    a["calendar_year_exposure"] = pd.Series(pd.NA, index=a.index, dtype="Int64")
    known_year = a["qualifying"] & a["adoption_year"].notna()
    a.loc[known_year, "calendar_year_exposure"] = a.loc[known_year, "adoption_year"]

    return a


def load_data(csv_path: Path, xlsx_path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    audit = pd.read_csv(csv_path)
    panel = pd.read_excel(xlsx_path, sheet_name="tourism_and_macroeconomic_data")

    required_audit = {
        "country", "iso3", "qualifying_program_found",
        "announcement_date", "launch_or_effective_date"
    }
    required_panel = {
        "country_name", "iso3", "year", OUTCOME, "gdp",
        "internet_usage_pct", "inflation_annual_pct"
    }

    missing_audit = required_audit - set(audit.columns)
    missing_panel = required_panel - set(panel.columns)
    if missing_audit:
        raise ValueError(f"Audit file is missing columns: {sorted(missing_audit)}")
    if missing_panel:
        raise ValueError(f"Panel file is missing columns: {sorted(missing_panel)}")

    audit["iso3"] = audit["iso3"].astype("string").str.upper().str.strip()
    audit = audit[audit["iso3"].notna() & audit["iso3"].ne("")].copy()
    panel["iso3"] = panel["iso3"].astype(str).str.upper().str.strip()
    panel["year"] = pd.to_numeric(panel["year"], errors="coerce").astype("Int64")

    if panel["iso3"].duplicated().any():
        # Duplicates by country-year are the relevant integrity check.
        dup = panel.duplicated(["iso3", "year"], keep=False)
        if dup.any():
            raise ValueError(
                "Panel contains duplicate country-year observations. "
                "Resolve these before estimation."
            )

    return build_treatment_variables(audit), panel


def prepare_panel(audit: pd.DataFrame, panel: pd.DataFrame) -> pd.DataFrame:
    """Merge audit treatment information and construct only lagged covariates."""
    p = panel.copy()

    treatment_cols = [
        "iso3", "qualifying", "program_name", "announcement_date",
        "launch_or_effective_date", "announcement_precision",
        "effective_precision", "announcement_date_parsed", "effective_date",
        "adoption_year", "adoption_month", "first_full_exposure_year",
        "calendar_year_exposure", "status_during_observation_period",
        "reason_for_exclusion"
    ]
    treatment_cols = [c for c in treatment_cols if c in audit.columns]

    p = p.merge(audit[treatment_cols], on="iso3", how="left", validate="many_to_one")

    p = p.sort_values(["iso3", "year"]).reset_index(drop=True)

    p["log_gdp"] = np.where(p["gdp"] > 0, np.log(p["gdp"]), np.nan)
    p["log_gdp_lag1"] = p.groupby("iso3")["log_gdp"].shift(1)
    p["inflation_annual_pct_lag1"] = p.groupby("iso3")["inflation_annual_pct"].shift(1)
    p["internet_usage_pct_lag1"] = p.groupby("iso3")["internet_usage_pct"].shift(1)

    return p


def main_sample(
    panel: pd.DataFrame,
    cohort_col: str = "first_full_exposure_year",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build the main precision-based sample.

    Treated countries must have:
      * a qualifying program;
      * an effective date with month/day precision;
      * an estimable post-treatment period in the observed panel.

    Countries with no qualifying program are never-treated.
    Countries with missing/ambiguous treatment dates are excluded.
    """
    p = panel.copy()
    max_year = int(p["year"].max())

    precise_treated = (
        p["qualifying"].fillna(False)
        & p[cohort_col].notna()
    )

    country = (
        p.groupby("iso3", as_index=False)
        .agg(
            qualifying=("qualifying", "max"),
            cohort=(cohort_col, "first"),
            effective_precision=("effective_precision", "first"),
            country_name=("country_name", "first"),
        )
    )

    country["is_never_treated"] = ~country["qualifying"].fillna(False)
    country["main_treated"] = (
        country["qualifying"].fillna(False)
        & country["cohort"].notna()
        & (country["cohort"].astype("float") < max_year)
    )


    keep_iso = set(
        country.loc[country["is_never_treated"] | country["main_treated"], "iso3"]
    )

    out = p[p["iso3"].isin(keep_iso)].copy()

    cohort_map = country.set_index("iso3")["cohort"].to_dict()
    out["cohort"] = out["iso3"].map(cohort_map)
    out["treated_main"] = (
        out["cohort"].notna()
        & (out["year"] >= out["cohort"])
    ).astype(int)

    return out, country


def sample_flow(panel: pd.DataFrame, audit: pd.DataFrame, country: pd.DataFrame) -> pd.DataFrame:
    """Return a compact sample-flow table for the paper."""
    all_countries = set(panel["iso3"].dropna().unique())
    qualifying = set(audit.loc[audit["qualifying"], "iso3"])
    precise = set(
        audit.loc[
            audit["qualifying"]
            & audit["effective_precision"].isin(["month", "day"])
            & audit["first_full_exposure_year"].notna(),
            "iso3"
        ]
    )
    never = all_countries - qualifying
    estimable = set(country.loc[country["main_treated"], "iso3"])
    ambiguous = qualifying - precise

    rows = [
        ("Countries in outcome panel", len(all_countries)),
        ("Countries with qualifying visa program", len(qualifying)),
        ("Never-treated countries", len(never)),
        ("Qualifying countries with month/day effective date", len(precise)),
        ("Qualifying countries with ambiguous/missing effective date", len(ambiguous)),
        ("Treated countries with at least one observed full post-treatment year", len(estimable)),
        ("Treatment cohorts supporting the main estimator", int(country.loc[country["main_treated"], "cohort"].nunique())),
    ]
    return pd.DataFrame(rows, columns=["item", "n"])


# Callaway--Sant'Anna-style group-time DID

def cs_group_time(
    data: pd.DataFrame,
    outcome: str = OUTCOME,
    cohort_col: str = "cohort",
) -> pd.DataFrame:
    """
    Unadjusted group-time DID using never-treated countries.

    For cohort g and year t >= g:
      ATT(g,t) =
        mean[Y_i,t - Y_i,g-1 | G_i=g]
        -
        mean[Y_i,t - Y_i,g-1 | never-treated]

    This is the simplest never-treated-control version of the
    Callaway--Sant'Anna group-time estimand. It is deliberately not presented
    as a solution to endogenous treatment adoption.
    """
    d = data.copy()
    d = d.dropna(subset=[outcome, "iso3", "year"])

    country_cohort = (
        d.groupby("iso3")[cohort_col]
        .first()
    )
    never = set(country_cohort[country_cohort.isna()].index)

    if not never:
        raise ValueError("No never-treated countries are available.")

    treated_cohorts = sorted(
        country_cohort.dropna().astype(int).unique().tolist()
    )

    records = []

    for g in treated_cohorts:
        treated_ids = set(country_cohort[country_cohort.eq(g)].index)
        base_year = g - 1

        base = (
            d[d["year"].eq(base_year)][["iso3", outcome]]
            .rename(columns={outcome: "y_base"})
        )

        for t in sorted(d.loc[d["year"].ge(g), "year"].unique()):
            yt = d[d["year"].eq(t)][["iso3", outcome]].rename(
                columns={outcome: "y_t"}
            )

            changes = yt.merge(base, on="iso3", how="inner")
            changes["delta"] = changes["y_t"] - changes["y_base"]

            tr = changes[changes["iso3"].isin(treated_ids)]["delta"].dropna()
            co = changes[changes["iso3"].isin(never)]["delta"].dropna()

            if len(tr) < 1 or len(co) < 2:
                continue

            est = tr.mean() - co.mean()
            var_tr = tr.var(ddof=1) / len(tr) if len(tr) > 1 else np.nan
            var_co = co.var(ddof=1) / len(co)
            se = np.sqrt(var_tr + var_co) if np.isfinite(var_tr) else np.nan

            records.append(
                {
                    "cohort": g,
                    "year": int(t),
                    "event_time": int(t - g),
                    "estimate": est,
                    "se": se,
                    "n_treated": len(tr),
                    "n_never": len(co),
                }
            )

    return pd.DataFrame(records)


def aggregate_event_time(gt: pd.DataFrame) -> pd.DataFrame:
    """Aggregate group-time estimates by event time using treated-country weights."""
    if gt.empty:
        return gt.copy()

    rows = []
    for e, sub in gt.groupby("event_time"):
        w = sub["n_treated"].to_numpy(dtype=float)
        y = sub["estimate"].to_numpy(dtype=float)

        if w.sum() == 0:
            continue

        est = np.average(y, weights=w)

        se = np.sqrt(
            np.average(
                np.square(sub["se"].fillna(0).to_numpy(dtype=float)),
                weights=w,
            )
        ) / np.sqrt(max(len(sub), 1))

        rows.append(
            {
                "event_time": int(e),
                "estimate": est,
                "se": se,
                "ci_low": est - 1.96 * se,
                "ci_high": est + 1.96 * se,
                "n_cohorts": int(sub["cohort"].nunique()),
                "n_treated_country_observations": int(sub["n_treated"].sum()),
            }
        )

    return pd.DataFrame(rows).sort_values("event_time")

# TWFE benchmark

def twfe_benchmark(data: pd.DataFrame, covariates: list[str] | None = None):
    """
    Conventional two-way fixed-effects benchmark.

    Treatment is the main annual first-full-exposure indicator. Country and
    year fixed effects are absorbed with categorical indicators.
    """
    covariates = covariates or BASE_COVARIATES
    d = data.copy()

    cols = [OUTCOME, "treated_main", "iso3", "year"] + covariates
    d = d[cols].dropna().copy()
    d["year"] = d["year"].astype(int)
    d["iso3"] = d["iso3"].astype(str)

    rhs = "treated_main"
    available_covars = [c for c in covariates if c in d.columns and d[c].notna().any()]
    if available_covars:
        rhs += " + " + " + ".join(available_covars)

    formula = f"{OUTCOME} ~ {rhs} + C(iso3) + C(year)"

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        model = smf.ols(formula, data=d).fit(
            cov_type="cluster",
            cov_kwds={"groups": d["iso3"]},
        )

    return model, d

# Semi-synthetic experiment

def exact_date_discrepancies(audit: pd.DataFrame) -> pd.DataFrame:
    """
    Return qualifying countries with both announcement and effective dates
    measured to month/day precision.

    The semi-synthetic experiment uses these observed discrepancies as the
    empirical source of treatment-date error.
    """
    a = audit.copy()

    both = (
        a["qualifying"]
        & a["announcement_date_parsed"].notna()
        & a["effective_date"].notna()
        & a["announcement_precision"].isin(["month", "day"])
        & a["effective_precision"].isin(["month", "day"])
    )

    out = a.loc[
        both,
        [
            "iso3", "announcement_date_parsed", "effective_date",
            "announcement_precision", "effective_precision"
        ]
    ].copy()

    out["announcement_year"] = out["announcement_date_parsed"].dt.year
    out["effective_year"] = out["effective_date"].dt.year

    out["announcement_full_year"] = np.where(
        out["announcement_date_parsed"].dt.month.eq(1),
        out["announcement_year"],
        out["announcement_year"] + 1,
    )
    out["effective_full_year"] = np.where(
        out["effective_date"].dt.month.eq(1),
        out["effective_year"],
        out["effective_year"] + 1,
    )
    out["date_error_years"] = (
        out["announcement_full_year"] - out["effective_full_year"]
    )

    return out


def make_synthetic_panel(
    real_panel: pd.DataFrame,
    true_cohorts: dict[str, int],
    beta: float,
    rng: np.random.Generator,
) -> pd.DataFrame:

    d = real_panel.copy()

    countries = sorted(d["iso3"].dropna().unique())
    years = sorted(d["year"].dropna().astype(int).unique())

    country_fe = {
        c: rng.normal(0.0, 1.5)
        for c in countries
    }
    country_trend = {
        c: rng.normal(0.0, 0.005)
        for c in countries
    }
    year_fe = {
        y: 0.20 * np.sin((y - min(years)) / 2.0)
        for y in years
    }

    gdp_z = (
        d["log_gdp"]
        - d["log_gdp"].groupby(d["year"]).transform("mean")
    )
    gdp_scale = gdp_z.std(skipna=True)
    if not np.isfinite(gdp_scale) or gdp_scale == 0:
        gdp_z = pd.Series(0.0, index=d.index)
    else:
        gdp_z = gdp_z.fillna(0.0) / gdp_scale

    errors = {}
    phi = 0.45
    for c in countries:
        prev = rng.normal(0.0, 0.7)
        for y in years:
            eps = rng.normal(0.0, 0.7)
            prev = phi * prev + eps
            errors[(c, y)] = prev

    y = []
    for idx, row in d.iterrows():
        c = row["iso3"]
        yr = int(row["year"])
        g = true_cohorts.get(c)
        treated = int(g is not None and yr >= g)

        value = (
            5.0
            + country_fe[c]
            + year_fe[yr]
            + country_trend[c] * (yr - min(years))
            + 0.20 * gdp_z.loc[idx]
            + beta * treated
            + errors[(c, yr)]
        )
        y.append(value)

    d["synthetic_unemployment"] = y
    return d


def run_twfe_on_synthetic(
    d: pd.DataFrame,
    cohort_map: dict[str, int],
    use_misdated: bool,
):
    """Estimate TWFE on a synthetic panel using true or misdated treatment."""
    x = d.copy()
    x["year"] = x["year"].astype(int)
    cohort = x["iso3"].map(cohort_map)
    x["synthetic_treat"] = (
        cohort.notna() & x["year"].ge(cohort)
    ).astype(int)

    formula = "synthetic_unemployment ~ synthetic_treat + C(iso3) + C(year)"
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        m = smf.ols(formula, data=x).fit(
            cov_type="cluster",
            cov_kwds={"groups": x["iso3"]},
        )
    return float(m.params["synthetic_treat"]), float(m.bse["synthetic_treat"])


def run_cs_on_synthetic(
    d: pd.DataFrame,
    cohort_map: dict[str, int],
):
    """Run the same never-treated group-time estimator on synthetic outcomes."""
    x = d.copy()
    x["cohort"] = x["iso3"].map(cohort_map)
    x["treated_main"] = (
        x["cohort"].notna() & x["year"].ge(x["cohort"])
    ).astype(int)

    gt = cs_group_time(x, outcome="synthetic_unemployment", cohort_col="cohort")
    if gt.empty:
        return np.nan, np.nan

    post = gt[gt["event_time"] >= 0].copy()
    if post.empty:
        return np.nan, np.nan

    w = post["n_treated"].to_numpy(dtype=float)
    est = np.average(post["estimate"], weights=w)
    se = np.sqrt(
        np.average(
            np.square(post["se"].fillna(0).to_numpy(dtype=float)),
            weights=w,
        )
    ) / np.sqrt(max(len(post), 1))

    return float(est), float(se)


def run_semi_synthetic(
    panel: pd.DataFrame,
    audit: pd.DataFrame,
    beta: float = -1.0,
    reps: int = 200,
    seed: int = 12345,
) -> tuple[pd.DataFrame, pd.DataFrame]:

    discrepancy = exact_date_discrepancies(audit)

    max_year = int(panel["year"].max())
    eff = audit.loc[
        audit["qualifying"]
        & audit["first_full_exposure_year"].notna()
        & (pd.to_numeric(audit["first_full_exposure_year"], errors="coerce") < max_year),
        ["iso3", "first_full_exposure_year"]
    ].copy()

    true_map = dict(
        zip(eff["iso3"], eff["first_full_exposure_year"].astype(int))
    )

    if not true_map:
        raise ValueError("No estimable precise treatment cohorts for simulation.")


    true_map = {
        k: v for k, v in true_map.items()
        if k in set(panel["iso3"])
    }

    ann_all = audit.loc[
        audit["qualifying"]
        & audit["announcement_date_parsed"].notna(),
        ["iso3", "announcement_date_parsed"]
    ].copy()
    ann_all["announcement_cohort"] = ann_all["announcement_date_parsed"].dt.year

    ann_map = dict(
        zip(ann_all["iso3"], ann_all["announcement_cohort"].astype(int))
    )
    ann_map = {k: v for k, v in ann_map.items() if k in true_map}

    discrepancy_map = {
        k: v for k, v in zip(
            discrepancy["iso3"],
            discrepancy["date_error_years"]
        ) if k in true_map
    }

    rng = np.random.default_rng(seed)
    records = []

    for r in range(reps):
        sim = make_synthetic_panel(panel, true_map, beta=beta, rng=rng)

        cs_true, cs_true_se = run_cs_on_synthetic(sim, true_map)
        twfe_true, twfe_true_se = run_twfe_on_synthetic(sim, true_map, False)

        misdated_map = true_map.copy()
        misdated_map.update(ann_map)

        cs_mis, cs_mis_se = run_cs_on_synthetic(sim, misdated_map)
        twfe_mis, twfe_mis_se = run_twfe_on_synthetic(sim, misdated_map, True)

        for estimator, estimate, se, date_definition in [
            ("CS-style", cs_true, cs_true_se, "effective"),
            ("CS-style", cs_mis, cs_mis_se, "announcement/misdated"),
            ("TWFE", twfe_true, twfe_true_se, "effective"),
            ("TWFE", twfe_mis, twfe_mis_se, "announcement/misdated"),
        ]:
            if np.isfinite(estimate):
                records.append(
                    {
                        "rep": r + 1,
                        "estimator": estimator,
                        "date_definition": date_definition,
                        "estimate": estimate,
                        "se": se,
                        "bias": estimate - beta,
                        "covered_95": (
                            np.isfinite(se)
                            and (estimate - 1.96 * se <= beta <= estimate + 1.96 * se)
                        ),
                        "sign_error": np.sign(estimate) != np.sign(beta),
                    }
                )

    results = pd.DataFrame(records)

    summary = (
        results.groupby(["estimator", "date_definition"], as_index=False)
        .agg(
            mean_estimate=("estimate", "mean"),
            mean_bias=("bias", "mean"),
            rmse=("bias", lambda x: float(np.sqrt(np.mean(np.square(x))))),
            coverage_95=("covered_95", "mean"),
            sign_error_rate=("sign_error", "mean"),
            repetitions=("estimate", "size"),
        )
    )

    meta = pd.DataFrame(
        {
            "item": [
                "true_effect",
                "simulation_repetitions",
                "precise_effective_cohorts_used",
                "observed_announcement/effective_discrepancies_used",
            ],
            "value": [
                beta,
                reps,
                len(true_map),
                len(discrepancy_map),
            ],
        }
    )

    return summary, meta


def plot_event_study(event_df: pd.DataFrame, output_path: Path) -> None:
    if event_df.empty:
        return

    plt.figure(figsize=(9, 5))
    plt.axhline(0, linewidth=1)
    plt.axvline(-0.5, linestyle="--", linewidth=1)

    x = event_df["event_time"].to_numpy()
    y = event_df["estimate"].to_numpy()
    lo = event_df["ci_low"].to_numpy()
    hi = event_df["ci_high"].to_numpy()

    plt.errorbar(
        x,
        y,
        yerr=[y - lo, hi - y],
        fmt="o-",
        capsize=3,
    )
    plt.xlabel("Event time (years relative to first full exposure)")
    plt.ylabel("Estimated association with visa adoption")
    plt.title("Event-Time Associations with Digital-Nomad Visa Adoption")
    plt.tight_layout()
    plt.savefig(output_path, dpi=180)
    plt.close()


def plot_real_trajectories(
    panel: pd.DataFrame,
    audit: pd.DataFrame,
    output_path: Path,
    max_cohorts: int = 10,
) -> None:
    """
    Plot mean unemployment around adoption for a readable descriptive figure.
    This is explicitly descriptive and is not an event-study estimator.
    """
    d = panel.copy()
    cohort = (
        audit.set_index("iso3")["first_full_exposure_year"]
        .to_dict()
    )
    d["cohort"] = d["iso3"].map(cohort)
    d = d.dropna(subset=["cohort", OUTCOME])

    if d.empty:
        return

    eligible = (
        d.groupby("iso3")["cohort"]
        .first()
        .dropna()
        .sort_values()
        .index[:max_cohorts]
    )
    d = d[d["iso3"].isin(eligible)].copy()
    d["event_time"] = d["year"] - d["cohort"]

    means = d.groupby("event_time")[OUTCOME].mean().sort_index()

    plt.figure(figsize=(9, 5))
    plt.plot(means.index, means.values, marker="o")
    plt.axvline(0, linestyle="--", linewidth=1)
    plt.xlabel("Event time (years relative to first full exposure)")
    plt.ylabel("Mean unemployment rate")
    plt.title("Descriptive Unemployment Trajectories Around Visa Adoption")
    plt.tight_layout()
    plt.savefig(output_path, dpi=180)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Professor-aligned staggered-adoption sensitivity analysis."
    )
    parser.add_argument("--audit", default=DEFAULT_CSV)
    parser.add_argument("--panel", default=DEFAULT_XLSX)
    parser.add_argument("--output-dir", default="results_dnm_sensitivity")
    parser.add_argument("--sim-reps", type=int, default=200)
    parser.add_argument("--sim-beta", type=float, default=-1.0)
    parser.add_argument("--seed", type=int, default=12345)
    args, _ = parser.parse_known_args()

    audit_path = Path(args.audit)
    panel_path = Path(args.panel)
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    audit, panel_raw = load_data(audit_path, panel_path)
    panel = prepare_panel(audit, panel_raw)

    main_panel, country = main_sample(panel)
    flow = sample_flow(panel, audit, country)

    audit.to_csv(out / "audit_with_treatment_dates.csv", index=False)
    flow.to_csv(out / "sample_flow.csv", index=False)


    gt = cs_group_time(main_panel, outcome=OUTCOME, cohort_col="cohort")
    event = aggregate_event_time(gt)

    gt.to_csv(out / "cs_group_time_associations.csv", index=False)
    event.to_csv(out / "cs_event_time_associations.csv", index=False)

    twfe_model, twfe_data = twfe_benchmark(main_panel, BASE_COVARIATES)

    twfe_table = pd.DataFrame(
        {
            "term": ["treated_main"],
            "estimate": [twfe_model.params.get("treated_main", np.nan)],
            "se": [twfe_model.bse.get("treated_main", np.nan)],
            "p_value": [twfe_model.pvalues.get("treated_main", np.nan)],
            "ci_low": [
                twfe_model.conf_int().loc["treated_main", 0]
                if "treated_main" in twfe_model.params else np.nan
            ],
            "ci_high": [
                twfe_model.conf_int().loc["treated_main", 1]
                if "treated_main" in twfe_model.params else np.nan
            ],
            "n_obs": [int(twfe_model.nobs)],
            "n_countries": [twfe_data["iso3"].nunique()],
        }
    )
    twfe_table.to_csv(out / "twfe_benchmark.csv", index=False)


    sensitivity_country = (
        panel.groupby("iso3", as_index=False)
        .agg(
            qualifying=("qualifying", "max"),
            full_exposure_year=("first_full_exposure_year", "first"),
            calendar_exposure_year=("calendar_year_exposure", "first"),
        )
    )
    sensitivity_country.to_csv(
        out / "treatment_date_sensitivity_country_level.csv",
        index=False,
    )

    # -------------------------------------------------------------
    # 5. Semi-synthetic experiment
    # -------------------------------------------------------------
    sim_summary, sim_meta = run_semi_synthetic(
        panel=panel,
        audit=audit,
        beta=args.sim_beta,
        reps=args.sim_reps,
        seed=args.seed,
    )
    sim_summary.to_csv(out / "semi_synthetic_summary.csv", index=False)
    sim_meta.to_csv(out / "semi_synthetic_metadata.csv", index=False)


    plot_event_study(
        event,
        out / "event_time_associations.svg",
    )
    plot_real_trajectories(
        panel,
        audit,
        out / "descriptive_unemployment_trajectories.svg",
    )

    # Save the analysis-ready panel.
    main_panel.to_csv(out / "analysis_panel_main.csv", index=False)


    print("\n=== Digital Nomad Visa Sensitivity Analysis ===")
    print("\nSample flow:")
    print(flow.to_string(index=False))

    print("\nCS-style event-time associations:")
    if event.empty:
        print("No estimable group-time/event-time estimates.")
    else:
        print(event.to_string(index=False))

    print("\nTWFE benchmark:")
    print(twfe_table.to_string(index=False))

    print("\nSemi-synthetic experiment:")
    print(sim_summary.to_string(index=False))

    print(f"\nResults written to: {out.resolve()}")


if __name__ == "__main__":
    main()

"""
Professor-aligned empirical analysis:
Digital Nomad Visa Adoption and Unemployment:
A Staggered-Adoption Sensitivity Analysis

Main goals
----------
1. Load and validate the Stage-1 audit and annual macro/tourism panel.
2. Construct transparent treatment-date variables without silently shifting dates.
3. Estimate group-time associations using a Callaway--Sant'Anna-style DID
   with never-treated countries as the comparison group.
4. Estimate conventional TWFE as a benchmark.
5. Describe real-data event-time associations and support.
6. Run a semi-synthetic experiment in which the true treatment effect is known
   and observed announcement/effective-date discrepancies are deliberately
   imposed.

Important interpretation
------------------------
The real-data estimates are ASSOCIATIONS, not causal effects. The script does
not use DML, contemporaneous post-treatment controls, or tourism variables as
confounder controls.

Dependencies
------------
pandas, numpy, statsmodels, openpyxl, matplotlib
"""

from __future__ import annotations

import argparse
import re
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt


# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

BASE_COVARIATES = [
    "log_gdp_lag1",
    "inflation_annual_pct_lag1",
    "internet_usage_pct_lag1",
]

OUTCOME = "unemployment_rate"

DEFAULT_CSV = "Completed_Stage1_Audit_190-4.csv"
DEFAULT_XLSX = "DigitalNomadDataset copy.xlsx"


# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------

def parse_date_precision(value: object) -> str:
    """Identify whether an audit date contains year, month, or day precision."""
    if pd.isna(value):
        return "missing"
    s = str(value).strip()
    if re.fullmatch(r"\d{4}", s):
        return "year"
    if re.fullmatch(r"\d{4}[-/]\d{1,2}", s):
        return "month"
    if re.fullmatch(r"\d{1,2}/\d{1,2}/\d{2,4}", s):
        return "day"
    # Try general parsing, but flag it as non-standard so it is not
    # silently treated as an exact date in the main specification.
    parsed = pd.to_datetime(s, errors="coerce")
    return "day" if pd.notna(parsed) else "other"


def parse_audit_date(value: object) -> pd.Timestamp:
    """Parse audit date values, returning NaT when unavailable."""
    if pd.isna(value):
        return pd.NaT
    return pd.to_datetime(str(value).strip(), errors="coerce")


def build_treatment_variables(audit: pd.DataFrame) -> pd.DataFrame:
    """
    Create exact implementation-date fields and a transparent annual cohort.

    Main annual cohort:
      - exact January implementation -> same calendar year;
      - exact month/day implementation after January -> first full calendar
        year after implementation;
      - year-only effective dates are retained for reporting but excluded from
        the precision-based main estimator because the month is unknown.

    This avoids the old blanket 'month >= 7' rule.
    """
    a = audit.copy()

    a["qualifying"] = (
        a["qualifying_program_found"]
        .astype("string")
        .str.lower()
        .eq("yes")
    )

    a["announcement_precision"] = a["announcement_date"].map(parse_date_precision)
    a["effective_precision"] = a["launch_or_effective_date"].map(parse_date_precision)

    a["announcement_date_parsed"] = a["announcement_date"].map(parse_audit_date)
    a["effective_date"] = a["launch_or_effective_date"].map(parse_audit_date)

    a["adoption_year"] = a["effective_date"].dt.year.astype("Int64")
    a["adoption_month"] = a["effective_date"].dt.month.astype("Int64")

    # First full calendar year of exposure. Exact January = current year;
    # otherwise the next calendar year. Unknown month is NOT guessed.
    a["first_full_exposure_year"] = pd.Series(pd.NA, index=a.index, dtype="Int64")
    exact = a["qualifying"] & a["effective_date"].notna() & (
        a["effective_precision"].isin(["month", "day"])
    )
    jan = exact & a["adoption_month"].eq(1)
    non_jan = exact & a["adoption_month"].gt(1)

    a.loc[jan, "first_full_exposure_year"] = a.loc[jan, "adoption_year"]
    a.loc[non_jan, "first_full_exposure_year"] = (
        a.loc[non_jan, "adoption_year"] + 1
    )

    # A second transparent date definition for sensitivity analysis:
    # treatment begins in the calendar year of implementation.
    a["calendar_year_exposure"] = pd.Series(pd.NA, index=a.index, dtype="Int64")
    known_year = a["qualifying"] & a["adoption_year"].notna()
    a.loc[known_year, "calendar_year_exposure"] = a.loc[known_year, "adoption_year"]

    return a


def load_data(csv_path: Path, xlsx_path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    audit = pd.read_csv(csv_path)
    panel = pd.read_excel(xlsx_path, sheet_name="tourism_and_macroeconomic_data")

    required_audit = {
        "country", "iso3", "qualifying_program_found",
        "announcement_date", "launch_or_effective_date"
    }
    required_panel = {
        "country_name", "iso3", "year", OUTCOME, "gdp",
        "internet_usage_pct", "inflation_annual_pct"
    }

    missing_audit = required_audit - set(audit.columns)
    missing_panel = required_panel - set(panel.columns)
    if missing_audit:
        raise ValueError(f"Audit file is missing columns: {sorted(missing_audit)}")
    if missing_panel:
        raise ValueError(f"Panel file is missing columns: {sorted(missing_panel)}")

    audit["iso3"] = audit["iso3"].astype("string").str.upper().str.strip()
    audit = audit[audit["iso3"].notna() & audit["iso3"].ne("")].copy()
    panel["iso3"] = panel["iso3"].astype(str).str.upper().str.strip()
    panel["year"] = pd.to_numeric(panel["year"], errors="coerce").astype("Int64")

    if panel["iso3"].duplicated().any():
        # Duplicates by country-year are the relevant integrity check.
        dup = panel.duplicated(["iso3", "year"], keep=False)
        if dup.any():
            raise ValueError(
                "Panel contains duplicate country-year observations. "
                "Resolve these before estimation."
            )

    return build_treatment_variables(audit), panel


def prepare_panel(audit: pd.DataFrame, panel: pd.DataFrame) -> pd.DataFrame:
    """Merge audit treatment information and construct only lagged covariates."""
    p = panel.copy()

    treatment_cols = [
        "iso3", "qualifying", "program_name", "announcement_date",
        "launch_or_effective_date", "announcement_precision",
        "effective_precision", "announcement_date_parsed", "effective_date",
        "adoption_year", "adoption_month", "first_full_exposure_year",
        "calendar_year_exposure", "status_during_observation_period",
        "reason_for_exclusion"
    ]
    treatment_cols = [c for c in treatment_cols if c in audit.columns]

    p = p.merge(audit[treatment_cols], on="iso3", how="left", validate="many_to_one")

    p = p.sort_values(["iso3", "year"]).reset_index(drop=True)

    # Predetermined/lagged covariates only.
    p["log_gdp"] = np.where(p["gdp"] > 0, np.log(p["gdp"]), np.nan)
    p["log_gdp_lag1"] = p.groupby("iso3")["log_gdp"].shift(1)
    p["inflation_annual_pct_lag1"] = p.groupby("iso3")["inflation_annual_pct"].shift(1)
    p["internet_usage_pct_lag1"] = p.groupby("iso3")["internet_usage_pct"].shift(1)

    return p


def main_sample(
    panel: pd.DataFrame,
    cohort_col: str = "first_full_exposure_year",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build the main precision-based sample.

    Treated countries must have:
      * a qualifying program;
      * an effective date with month/day precision;
      * an estimable post-treatment period in the observed panel.

    Countries with no qualifying program are never-treated.
    Countries with missing/ambiguous treatment dates are excluded.
    """
    p = panel.copy()
    max_year = int(p["year"].max())

    precise_treated = (
        p["qualifying"].fillna(False)
        & p[cohort_col].notna()
    )

    # Country-level treatment status.
    country = (
        p.groupby("iso3", as_index=False)
        .agg(
            qualifying=("qualifying", "max"),
            cohort=(cohort_col, "first"),
            effective_precision=("effective_precision", "first"),
            country_name=("country_name", "first"),
        )
    )

    country["is_never_treated"] = ~country["qualifying"].fillna(False)
    country["main_treated"] = (
        country["qualifying"].fillna(False)
        & country["cohort"].notna()
        & (country["cohort"].astype("float") < max_year)
    )

    # Keep never-treated and treated countries with at least one full
    # post-treatment year observed.
    keep_iso = set(
        country.loc[country["is_never_treated"] | country["main_treated"], "iso3"]
    )

    out = p[p["iso3"].isin(keep_iso)].copy()

    # Main treatment indicator: first full exposure year onward.
    cohort_map = country.set_index("iso3")["cohort"].to_dict()
    out["cohort"] = out["iso3"].map(cohort_map)
    out["treated_main"] = (
        out["cohort"].notna()
        & (out["year"] >= out["cohort"])
    ).astype(int)

    return out, country


def sample_flow(panel: pd.DataFrame, audit: pd.DataFrame, country: pd.DataFrame) -> pd.DataFrame:
    """Return a compact sample-flow table for the paper."""
    all_countries = set(panel["iso3"].dropna().unique())
    qualifying = set(audit.loc[audit["qualifying"], "iso3"])
    precise = set(
        audit.loc[
            audit["qualifying"]
            & audit["effective_precision"].isin(["month", "day"])
            & audit["first_full_exposure_year"].notna(),
            "iso3"
        ]
    )
    never = all_countries - qualifying
    estimable = set(country.loc[country["main_treated"], "iso3"])
    ambiguous = qualifying - precise

    rows = [
        ("Countries in outcome panel", len(all_countries)),
        ("Countries with qualifying visa program", len(qualifying)),
        ("Never-treated countries", len(never)),
        ("Qualifying countries with month/day effective date", len(precise)),
        ("Qualifying countries with ambiguous/missing effective date", len(ambiguous)),
        ("Treated countries with at least one observed full post-treatment year", len(estimable)),
        ("Treatment cohorts supporting the main estimator", int(country.loc[country["main_treated"], "cohort"].nunique())),
    ]
    return pd.DataFrame(rows, columns=["item", "n"])


# ---------------------------------------------------------------------
# Callaway--Sant'Anna-style group-time DID
# ---------------------------------------------------------------------

def cs_group_time(
    data: pd.DataFrame,
    outcome: str = OUTCOME,
    cohort_col: str = "cohort",
) -> pd.DataFrame:
    """
    Unadjusted group-time DID using never-treated countries.

    For cohort g and year t >= g:
      ATT(g,t) =
        mean[Y_i,t - Y_i,g-1 | G_i=g]
        -
        mean[Y_i,t - Y_i,g-1 | never-treated]

    This is the simplest never-treated-control version of the
    Callaway--Sant'Anna group-time estimand. It is deliberately not presented
    as a solution to endogenous treatment adoption.
    """
    d = data.copy()
    d = d.dropna(subset=[outcome, "iso3", "year"])

    country_cohort = (
        d.groupby("iso3")[cohort_col]
        .first()
    )
    never = set(country_cohort[country_cohort.isna()].index)

    if not never:
        raise ValueError("No never-treated countries are available.")

    treated_cohorts = sorted(
        country_cohort.dropna().astype(int).unique().tolist()
    )

    records = []

    for g in treated_cohorts:
        treated_ids = set(country_cohort[country_cohort.eq(g)].index)
        base_year = g - 1

        # Need the pre-treatment outcome for every country contributing to the
        # relevant contrast.
        base = (
            d[d["year"].eq(base_year)][["iso3", outcome]]
            .rename(columns={outcome: "y_base"})
        )

        for t in sorted(d.loc[d["year"].ge(g), "year"].unique()):
            yt = d[d["year"].eq(t)][["iso3", outcome]].rename(
                columns={outcome: "y_t"}
            )

            changes = yt.merge(base, on="iso3", how="inner")
            changes["delta"] = changes["y_t"] - changes["y_base"]

            tr = changes[changes["iso3"].isin(treated_ids)]["delta"].dropna()
            co = changes[changes["iso3"].isin(never)]["delta"].dropna()

            if len(tr) < 1 or len(co) < 2:
                continue

            est = tr.mean() - co.mean()
            var_tr = tr.var(ddof=1) / len(tr) if len(tr) > 1 else np.nan
            var_co = co.var(ddof=1) / len(co)
            se = np.sqrt(var_tr + var_co) if np.isfinite(var_tr) else np.nan

            records.append(
                {
                    "cohort": g,
                    "year": int(t),
                    "event_time": int(t - g),
                    "estimate": est,
                    "se": se,
                    "n_treated": len(tr),
                    "n_never": len(co),
                }
            )

    return pd.DataFrame(records)


def aggregate_event_time(gt: pd.DataFrame) -> pd.DataFrame:
    """Aggregate group-time estimates by event time using treated-country weights."""
    if gt.empty:
        return gt.copy()

    rows = []
    for e, sub in gt.groupby("event_time"):
        w = sub["n_treated"].to_numpy(dtype=float)
        y = sub["estimate"].to_numpy(dtype=float)

        if w.sum() == 0:
            continue

        est = np.average(y, weights=w)

        # A transparent heterogeneity-weighted standard error approximation.
        # The script reports this as an aggregation SE, not a causal inference
        # guarantee.
        se = np.sqrt(
            np.average(
                np.square(sub["se"].fillna(0).to_numpy(dtype=float)),
                weights=w,
            )
        ) / np.sqrt(max(len(sub), 1))

        rows.append(
            {
                "event_time": int(e),
                "estimate": est,
                "se": se,
                "ci_low": est - 1.96 * se,
                "ci_high": est + 1.96 * se,
                "n_cohorts": int(sub["cohort"].nunique()),
                "n_treated_country_observations": int(sub["n_treated"].sum()),
            }
        )

    return pd.DataFrame(rows).sort_values("event_time")


# ---------------------------------------------------------------------
# TWFE benchmark
# ---------------------------------------------------------------------

def twfe_benchmark(data: pd.DataFrame, covariates: list[str] | None = None):
    """
    Conventional two-way fixed-effects benchmark.

    Treatment is the main annual first-full-exposure indicator. Country and
    year fixed effects are absorbed with categorical indicators.
    """
    covariates = covariates or BASE_COVARIATES
    d = data.copy()

    cols = [OUTCOME, "treated_main", "iso3", "year"] + covariates
    d = d[cols].dropna().copy()
    d["year"] = d["year"].astype(int)
    d["iso3"] = d["iso3"].astype(str)

    rhs = "treated_main"
    available_covars = [c for c in covariates if c in d.columns and d[c].notna().any()]
    if available_covars:
        rhs += " + " + " + ".join(available_covars)

    formula = f"{OUTCOME} ~ {rhs} + C(iso3) + C(year)"

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        model = smf.ols(formula, data=d).fit(
            cov_type="cluster",
            cov_kwds={"groups": d["iso3"]},
        )

    return model, d


# ---------------------------------------------------------------------
# Semi-synthetic experiment
# ---------------------------------------------------------------------

def exact_date_discrepancies(audit: pd.DataFrame) -> pd.DataFrame:
    """
    Return qualifying countries with both announcement and effective dates
    measured to month/day precision.

    The semi-synthetic experiment uses these observed discrepancies as the
    empirical source of treatment-date error.
    """
    a = audit.copy()

    both = (
        a["qualifying"]
        & a["announcement_date_parsed"].notna()
        & a["effective_date"].notna()
        & a["announcement_precision"].isin(["month", "day"])
        & a["effective_precision"].isin(["month", "day"])
    )

    out = a.loc[
        both,
        [
            "iso3", "announcement_date_parsed", "effective_date",
            "announcement_precision", "effective_precision"
        ]
    ].copy()

    out["announcement_year"] = out["announcement_date_parsed"].dt.year
    out["effective_year"] = out["effective_date"].dt.year

    # Annual outcomes cannot represent within-year timing exactly. For the
    # simulation, the observed error is therefore represented as a shift in
    # the first full-exposure year implied by each date.
    out["announcement_full_year"] = np.where(
        out["announcement_date_parsed"].dt.month.eq(1),
        out["announcement_year"],
        out["announcement_year"] + 1,
    )
    out["effective_full_year"] = np.where(
        out["effective_date"].dt.month.eq(1),
        out["effective_year"],
        out["effective_year"] + 1,
    )
    out["date_error_years"] = (
        out["announcement_full_year"] - out["effective_full_year"]
    )

    return out


def make_synthetic_panel(
    real_panel: pd.DataFrame,
    true_cohorts: dict[str, int],
    beta: float,
    rng: np.random.Generator,
) -> pd.DataFrame:
    """
    Generate unemployment with a known treatment effect while preserving the
    observed countries, years, and adoption cohorts.

    Outcome DGP:
      country FE + year FE + beta * true treatment + country trend +
      lagged-GDP signal + AR(1)-like noise.

    The covariates are only used to generate the synthetic outcome. They are
    not used to claim identification in the real-data analysis.
    """
    d = real_panel.copy()

    countries = sorted(d["iso3"].dropna().unique())
    years = sorted(d["year"].dropna().astype(int).unique())

    country_fe = {
        c: rng.normal(0.0, 1.5)
        for c in countries
    }
    country_trend = {
        c: rng.normal(0.0, 0.005)
        for c in countries
    }
    year_fe = {
        y: 0.20 * np.sin((y - min(years)) / 2.0)
        for y in years
    }

    # Scale GDP signal so it contributes modestly to the outcome.
    gdp_z = (
        d["log_gdp"]
        - d["log_gdp"].groupby(d["year"]).transform("mean")
    )
    gdp_scale = gdp_z.std(skipna=True)
    if not np.isfinite(gdp_scale) or gdp_scale == 0:
        gdp_z = pd.Series(0.0, index=d.index)
    else:
        gdp_z = gdp_z.fillna(0.0) / gdp_scale

    errors = {}
    phi = 0.45
    for c in countries:
        prev = rng.normal(0.0, 0.7)
        for y in years:
            eps = rng.normal(0.0, 0.7)
            prev = phi * prev + eps
            errors[(c, y)] = prev

    y = []
    for idx, row in d.iterrows():
        c = row["iso3"]
        yr = int(row["year"])
        g = true_cohorts.get(c)
        treated = int(g is not None and yr >= g)

        value = (
            5.0
            + country_fe[c]
            + year_fe[yr]
            + country_trend[c] * (yr - min(years))
            + 0.20 * gdp_z.loc[idx]
            + beta * treated
            + errors[(c, yr)]
        )
        y.append(value)

    d["synthetic_unemployment"] = y
    return d


def run_twfe_on_synthetic(
    d: pd.DataFrame,
    cohort_map: dict[str, int],
    use_misdated: bool,
):
    """Estimate TWFE on a synthetic panel using true or misdated treatment."""
    x = d.copy()
    x["year"] = x["year"].astype(int)
    cohort = x["iso3"].map(cohort_map)
    x["synthetic_treat"] = (
        cohort.notna() & x["year"].ge(cohort)
    ).astype(int)

    formula = "synthetic_unemployment ~ synthetic_treat + C(iso3) + C(year)"
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        m = smf.ols(formula, data=x).fit(
            cov_type="cluster",
            cov_kwds={"groups": x["iso3"]},
        )
    return float(m.params["synthetic_treat"]), float(m.bse["synthetic_treat"])


def run_cs_on_synthetic(
    d: pd.DataFrame,
    cohort_map: dict[str, int],
):
    """Run the same never-treated group-time estimator on synthetic outcomes."""
    x = d.copy()
    x["cohort"] = x["iso3"].map(cohort_map)
    x["treated_main"] = (
        x["cohort"].notna() & x["year"].ge(x["cohort"])
    ).astype(int)

    gt = cs_group_time(x, outcome="synthetic_unemployment", cohort_col="cohort")
    if gt.empty:
        return np.nan, np.nan

    # Average post-treatment group-time associations using treated-country
    # weights. This is the scalar summary used for bias/coverage/sign error.
    post = gt[gt["event_time"] >= 0].copy()
    if post.empty:
        return np.nan, np.nan

    w = post["n_treated"].to_numpy(dtype=float)
    est = np.average(post["estimate"], weights=w)
    se = np.sqrt(
        np.average(
            np.square(post["se"].fillna(0).to_numpy(dtype=float)),
            weights=w,
        )
    ) / np.sqrt(max(len(post), 1))

    return float(est), float(se)


def run_semi_synthetic(
    panel: pd.DataFrame,
    audit: pd.DataFrame,
    beta: float = -1.0,
    reps: int = 200,
    seed: int = 12345,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Semi-synthetic experiment.

    The actual adoption structure is preserved for countries with precise
    effective dates. Observed announcement/effective discrepancies are used
    to construct a deliberately misdated treatment cohort.

    Countries whose effective cohort is outside the observed panel are not
    useful for the experiment because they cannot contribute post-treatment
    outcomes.
    """
    discrepancy = exact_date_discrepancies(audit)

    max_year = int(panel["year"].max())

    # Use precise effective cohorts that can actually generate post-treatment
    # observations in the panel.
    eff = audit.loc[
        audit["qualifying"]
        & audit["first_full_exposure_year"].notna()
        & (pd.to_numeric(audit["first_full_exposure_year"], errors="coerce") < max_year),
        ["iso3", "first_full_exposure_year"]
    ].copy()

    true_map = dict(
        zip(eff["iso3"], eff["first_full_exposure_year"].astype(int))
    )

    if not true_map:
        raise ValueError("No estimable precise treatment cohorts for simulation.")

    # Only countries in the actual panel are used.
    true_map = {
        k: v for k, v in true_map.items()
        if k in set(panel["iso3"])
    }

    # Observed announcement/effective discrepancies. If announcement timing
    # is earlier/later, the misdated cohort reflects that observed error.
    # For the deliberate misdating exercise, use the observed announcement
    # calendar year as the erroneous treatment cohort. This intentionally
    # allows year-only announcement records to create the kind of timing
    # mismatch the sensitivity analysis is designed to study.
    ann_all = audit.loc[
        audit["qualifying"]
        & audit["announcement_date_parsed"].notna(),
        ["iso3", "announcement_date_parsed"]
    ].copy()
    ann_all["announcement_cohort"] = ann_all["announcement_date_parsed"].dt.year

    ann_map = dict(
        zip(ann_all["iso3"], ann_all["announcement_cohort"].astype(int))
    )
    ann_map = {k: v for k, v in ann_map.items() if k in true_map}

    # Keep the experiment metadata focused on cases for which an observed
    # announcement/effective discrepancy exists at the annual level.
    discrepancy_map = {
        k: v for k, v in zip(
            discrepancy["iso3"],
            discrepancy["date_error_years"]
        ) if k in true_map
    }

    rng = np.random.default_rng(seed)
    records = []

    for r in range(reps):
        sim = make_synthetic_panel(panel, true_map, beta=beta, rng=rng)

        # True treatment-date analysis.
        cs_true, cs_true_se = run_cs_on_synthetic(sim, true_map)
        twfe_true, twfe_true_se = run_twfe_on_synthetic(sim, true_map, False)

        # Misdated treatment map: use observed announcement cohort where
        # available; otherwise retain the true effective cohort.
        misdated_map = true_map.copy()
        misdated_map.update(ann_map)

        cs_mis, cs_mis_se = run_cs_on_synthetic(sim, misdated_map)
        twfe_mis, twfe_mis_se = run_twfe_on_synthetic(sim, misdated_map, True)

        for estimator, estimate, se, date_definition in [
            ("CS-style", cs_true, cs_true_se, "effective"),
            ("CS-style", cs_mis, cs_mis_se, "announcement/misdated"),
            ("TWFE", twfe_true, twfe_true_se, "effective"),
            ("TWFE", twfe_mis, twfe_mis_se, "announcement/misdated"),
        ]:
            if np.isfinite(estimate):
                records.append(
                    {
                        "rep": r + 1,
                        "estimator": estimator,
                        "date_definition": date_definition,
                        "estimate": estimate,
                        "se": se,
                        "bias": estimate - beta,
                        "covered_95": (
                            np.isfinite(se)
                            and (estimate - 1.96 * se <= beta <= estimate + 1.96 * se)
                        ),
                        "sign_error": np.sign(estimate) != np.sign(beta),
                    }
                )

    results = pd.DataFrame(records)

    summary = (
        results.groupby(["estimator", "date_definition"], as_index=False)
        .agg(
            mean_estimate=("estimate", "mean"),
            mean_bias=("bias", "mean"),
            rmse=("bias", lambda x: float(np.sqrt(np.mean(np.square(x))))),
            coverage_95=("covered_95", "mean"),
            sign_error_rate=("sign_error", "mean"),
            repetitions=("estimate", "size"),
        )
    )

    meta = pd.DataFrame(
        {
            "item": [
                "true_effect",
                "simulation_repetitions",
                "precise_effective_cohorts_used",
                "observed_announcement/effective_discrepancies_used",
            ],
            "value": [
                beta,
                reps,
                len(true_map),
                len(discrepancy_map),
            ],
        }
    )

    return summary, meta


# ---------------------------------------------------------------------
# Descriptive plots
# ---------------------------------------------------------------------
#
# Design choices (see docstring notes inline):
#   - Okabe-Ito colorblind-safe palette, color paired with marker/linestyle
#     so encoding survives grayscale printing.
#   - Object-oriented Matplotlib API + constrained layout instead of the
#     pyplot global-state calls + tight_layout() (the two layout engines
#     can conflict when mixed).
#   - CI level stated explicitly in the axis label; an interval means
#     nothing without saying what it is.
#   - Any omitted/normalized reference period is drawn as an explicit
#     marker rather than left as an unexplained gap in the line.
#   - The descriptive trajectory plot shows the number of countries behind
#     each point (N), since the panel is unbalanced across event time as
#     cohorts enter, and that was previously invisible.
#   - Exported at 300 dpi with editable SVG text, and plt.show() is called
#     so the figure also renders inline in Colab/Jupyter.

import matplotlib as mpl

# Okabe-Ito colorblind-safe palette (Okabe & Ito, 2008).
COLOR_ESTIMATE = "#0072B2"    # blue
COLOR_CI = "#000000"          # black
COLOR_REFERENCE = "#D55E00"   # vermillion
COLOR_ZERO = "#666666"        # neutral gray, distinct from data color
COLOR_INDIVIDUAL = "#999999"  # light gray for background trajectories
COLOR_COUNT_BARS = "#CCCCCC"  # light gray for N bars

_PLOT_RC = {
    "font.size": 10,
    "axes.titlesize": 12,
    "axes.titleweight": "bold",
    "axes.labelsize": 10,
    "legend.fontsize": 9,
    "svg.fonttype": "none",  # keep SVG text editable/searchable
}


def _apply_base_style(ax: plt.Axes) -> None:
    """Shared axis styling: light y-grid behind the data, no top/right spines."""
    ax.set_axisbelow(True)
    ax.grid(True, axis="y", linewidth=0.5, alpha=0.3, zorder=0)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(direction="out")


def plot_event_study(
    event_df: pd.DataFrame,
    output_path: Path,
    reference_time: float | None = None,
    ci_level: float = 95.0,
) -> None:
    """
    Plot event-time coefficient estimates with confidence intervals.

    reference_time: the omitted/normalized event-time period (e.g. -1), if
    the estimator has one. If it is not present in event_df, it is drawn
    explicitly as a zero-effect marker instead of appearing as an
    unexplained gap. Leave as None if the estimator has no such period.
    ci_level: confidence level of ci_low/ci_high, stated on the axis.
    """
    if event_df.empty:
        return

    output_path = Path(output_path).with_suffix(".svg")

    d = event_df.sort_values("event_time").reset_index(drop=True)
    x = d["event_time"].to_numpy(dtype=float)
    y = d["estimate"].to_numpy(dtype=float)
    lo = d["ci_low"].to_numpy(dtype=float)
    hi = d["ci_high"].to_numpy(dtype=float)

    yerr_low = y - lo
    yerr_high = hi - y
    if np.any(yerr_low < 0) or np.any(yerr_high < 0):
        raise ValueError(
            "ci_low must be <= estimate <= ci_high for every event_time; "
            "found an inverted interval."
        )

    with mpl.rc_context(_PLOT_RC):
        fig, ax = plt.subplots(figsize=(9, 5), layout="constrained")

        ax.axhline(0, color=COLOR_ZERO, linewidth=1, zorder=1)
        ax.axvline(
            -0.5,
            color=COLOR_ZERO,
            linestyle="--",
            linewidth=1,
            zorder=1,
            label="Full exposure begins",
        )

        ax.errorbar(
            x,
            y,
            yerr=[yerr_low, yerr_high],
            fmt="o-",
            color=COLOR_ESTIMATE,
            ecolor=COLOR_CI,
            elinewidth=1,
            capsize=3,
            markersize=5,
            label=f"Estimate ({ci_level:.0f}% CI)",
            zorder=3,
        )

        if reference_time is not None and not np.isclose(x, reference_time).any():
            ax.scatter(
                [reference_time],
                [0],
                marker="D",
                s=40,
                color=COLOR_REFERENCE,
                zorder=4,
                label=f"Reference period (t={reference_time:g}, normalized to 0)",
            )

        ax.set_xlabel("Event time (years relative to first full exposure)")
        ax.set_ylabel(f"Estimated association with visa adoption ({ci_level:.0f}% CI)")
        ax.set_title("Event-Time Associations with Digital-Nomad Visa Adoption")

        tick_lo = x.min() if reference_time is None else min(x.min(), reference_time)
        tick_hi = x.max() if reference_time is None else max(x.max(), reference_time)
        ax.set_xticks(np.arange(np.floor(tick_lo), np.ceil(tick_hi) + 1))

        _apply_base_style(ax)
        ax.legend(frameon=False, loc="best")

        fig.savefig(
            output_path,
            dpi=300,
            facecolor="white",
            metadata={
                "Description": (
                    "Event-study coefficients with confidence intervals. "
                    f"CI level: {ci_level:.0f}%. Vertical dashed line marks "
                    "the start of full exposure."
                )
            },
        )
        plt.show()
        plt.close(fig)


def plot_real_trajectories(
    panel: pd.DataFrame,
    audit: pd.DataFrame,
    output_path: Path,
    max_cohorts: int = 10,
    min_n_countries: int = 3,
) -> None:
    """
    Plot mean unemployment around adoption for a readable descriptive figure.
    This is explicitly descriptive and is not an event-study estimator.

    Because cohorts enter the panel at different calendar years, the number
    of countries behind the mean varies by event_time (the panel is
    unbalanced). That count is plotted on a secondary axis, and points
    supported by fewer than `min_n_countries` are shown with reduced
    emphasis rather than looking as trustworthy as the well-supported
    middle of the series.
    """
    output_path = Path(output_path).with_suffix(".svg")

    d = panel.copy()
    cohort = (
        audit.set_index("iso3")["first_full_exposure_year"]
        .to_dict()
    )
    d["cohort"] = d["iso3"].map(cohort)
    d = d.dropna(subset=["cohort", OUTCOME])

    if d.empty:
        return

    first_cohort_year = d.groupby("iso3")["cohort"].first().dropna().sort_values()
    n_available = first_cohort_year.shape[0]
    eligible = first_cohort_year.index[:max_cohorts]
    d = d[d["iso3"].isin(eligible)].copy()
    d["event_time"] = d["year"] - d["cohort"]

    grouped = d.groupby("event_time")[OUTCOME]
    means = grouped.mean().sort_index()
    counts = grouped.count().reindex(means.index)
    thin = counts.to_numpy() < min_n_countries

    with mpl.rc_context(_PLOT_RC):
        fig, ax = plt.subplots(figsize=(9, 5.5), layout="constrained")

        # Faint individual-country trajectories behind the mean, so the
        # aggregate line doesn't imply more homogeneity than the data has.
        for _, g in d.groupby("iso3"):
            g = g.sort_values("event_time")
            ax.plot(
                g["event_time"],
                g[OUTCOME],
                color=COLOR_INDIVIDUAL,
                linewidth=0.7,
                alpha=0.35,
                zorder=1,
            )

        ax.plot(
            means.index[~thin],
            means.values[~thin],
            marker="o",
            color=COLOR_ESTIMATE,
            linewidth=2,
            zorder=3,
            label=f"Cohort mean (n \u2265 {min_n_countries} countries)",
        )
        if thin.any():
            ax.plot(
                means.index[thin],
                means.values[thin],
                marker="o",
                linestyle="none",
                color=COLOR_ESTIMATE,
                alpha=0.4,
                markeredgecolor=COLOR_REFERENCE,
                markeredgewidth=1.2,
                zorder=3,
                label=f"Mean (n < {min_n_countries} countries)",
            )

        ax.axvline(0, color=COLOR_ZERO, linestyle="--", linewidth=1, zorder=1)

        ax2 = ax.twinx()
        ax2.bar(
            counts.index,
            counts.values,
            width=0.6,
            color=COLOR_COUNT_BARS,
            alpha=0.4,
            zorder=0,
        )
        ax2.set_ylabel("Countries contributing (N)", color="#666666")
        ax2.set_ylim(0, n_available)
        ax2.tick_params(colors="#666666")
        ax2.spines["top"].set_visible(False)
        ax.set_zorder(ax2.get_zorder() + 1)
        ax.patch.set_visible(False)

        ax.set_xlabel("Event time (years relative to first full exposure)")
        ax.set_ylabel("Mean unemployment rate")
        ax.set_title(
            "Descriptive Unemployment Trajectories Around Visa Adoption\n"
            f"(earliest {len(eligible)} of {n_available} adopting countries; "
            "unbalanced panel)"
        )
        _apply_base_style(ax)
        ax.legend(frameon=False, loc="best")

        fig.savefig(
            output_path,
            dpi=300,
            facecolor="white",
            metadata={
                "Description": (
                    "Descriptive (non-causal) mean unemployment by event "
                    f"time. Sample restricted to the earliest {len(eligible)} "
                    f"of {n_available} adopting countries by first-full-"
                    "exposure year; panel is unbalanced, N per point shown "
                    f"on secondary axis; points with n<{min_n_countries} "
                    "are flagged."
                )
            },
        )
        plt.show()
        plt.close(fig)


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Professor-aligned staggered-adoption sensitivity analysis."
    )
    parser.add_argument("--audit", default=DEFAULT_CSV)
    parser.add_argument("--panel", default=DEFAULT_XLSX)
    parser.add_argument("--output-dir", default="results_dnm_sensitivity")
    parser.add_argument("--sim-reps", type=int, default=200)
    parser.add_argument("--sim-beta", type=float, default=-1.0)
    parser.add_argument("--seed", type=int, default=12345)
    args, _ = parser.parse_known_args()

    audit_path = Path(args.audit)
    panel_path = Path(args.panel)
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    audit, panel_raw = load_data(audit_path, panel_path)
    panel = prepare_panel(audit, panel_raw)

    # -------------------------------------------------------------
    # 1. Sample flow
    # -------------------------------------------------------------
    main_panel, country = main_sample(panel)
    flow = sample_flow(panel, audit, country)

    audit.to_csv(out / "audit_with_treatment_dates.csv", index=False)
    flow.to_csv(out / "sample_flow.csv", index=False)

    # -------------------------------------------------------------
    # 2. Main CS-style group-time associations
    # -------------------------------------------------------------
    gt = cs_group_time(main_panel, outcome=OUTCOME, cohort_col="cohort")
    event = aggregate_event_time(gt)

    gt.to_csv(out / "cs_group_time_associations.csv", index=False)
    event.to_csv(out / "cs_event_time_associations.csv", index=False)

    # -------------------------------------------------------------
    # 3. TWFE benchmark
    # -------------------------------------------------------------
    twfe_model, twfe_data = twfe_benchmark(main_panel, BASE_COVARIATES)

    twfe_table = pd.DataFrame(
        {
            "term": ["treated_main"],
            "estimate": [twfe_model.params.get("treated_main", np.nan)],
            "se": [twfe_model.bse.get("treated_main", np.nan)],
            "p_value": [twfe_model.pvalues.get("treated_main", np.nan)],
            "ci_low": [
                twfe_model.conf_int().loc["treated_main", 0]
                if "treated_main" in twfe_model.params else np.nan
            ],
            "ci_high": [
                twfe_model.conf_int().loc["treated_main", 1]
                if "treated_main" in twfe_model.params else np.nan
            ],
            "n_obs": [int(twfe_model.nobs)],
            "n_countries": [twfe_data["iso3"].nunique()],
        }
    )
    twfe_table.to_csv(out / "twfe_benchmark.csv", index=False)

    # -------------------------------------------------------------
    # 4. Date sensitivity: calendar-year implementation vs first
    #    full exposure year
    # -------------------------------------------------------------
    sensitivity_country = (
        panel.groupby("iso3", as_index=False)
        .agg(
            qualifying=("qualifying", "max"),
            full_exposure_year=("first_full_exposure_year", "first"),
            calendar_exposure_year=("calendar_year_exposure", "first"),
        )
    )
    sensitivity_country.to_csv(
        out / "treatment_date_sensitivity_country_level.csv",
        index=False,
    )

    # -------------------------------------------------------------
    # 5. Semi-synthetic experiment
    # -------------------------------------------------------------
    sim_summary, sim_meta = run_semi_synthetic(
        panel=panel,
        audit=audit,
        beta=args.sim_beta,
        reps=args.sim_reps,
        seed=args.seed,
    )
    sim_summary.to_csv(out / "semi_synthetic_summary.csv", index=False)
    sim_meta.to_csv(out / "semi_synthetic_metadata.csv", index=False)

    # -------------------------------------------------------------
    # 6. Descriptive real-data dynamics
    # -------------------------------------------------------------
    plot_event_study(
        event,
        out / "event_time_associations.svg",
    )
    plot_real_trajectories(
        panel,
        audit,
        out / "descriptive_unemployment_trajectories.svg",
    )

    # Save the analysis-ready panel.
    main_panel.to_csv(out / "analysis_panel_main.csv", index=False)

    # -------------------------------------------------------------
    # 7. Console summary
    # -------------------------------------------------------------
    print("\n=== Digital Nomad Visa Sensitivity Analysis ===")
    print("\nSample flow:")
    print(flow.to_string(index=False))

    print("\nCS-style event-time associations:")
    if event.empty:
        print("No estimable group-time/event-time estimates.")
    else:
        print(event.to_string(index=False))

    print("\nTWFE benchmark:")
    print(twfe_table.to_string(index=False))

    print("\nSemi-synthetic experiment:")
    print(sim_summary.to_string(index=False))

    print(f"\nResults written to: {out.resolve()}")


if __name__ == "__main__":
    main()
